### ISSUE TITLE
Implement Navbar in the Dashboard

### ISSUE THREAD

**Issue by MPSxDev** [PayStell/paystell-website#9] opened 2024-11-21 04:33 UTC
### Description
A left-side navigation bar (navbar) needs to be created for the dashboard. This navbar should facilitate easy navigation between different sections of the dashboard.

### Requirements
- **Responsive Design:** The navbar must adapt to various screen sizes.
- **Included:**
  - Dashboard `/dashboard`
  - Your Money `/dashboard/money`
  - Payment links `/dashboard/links`
  - Sales `/dashboard/sales`
  - Settings `/dashboard/settings`
- **Interactivity:** It should include visual effects to indicate the active link.
- **Accessibility:** Ensure that the navbar complies with accessibility guidelines.

### Technical Considerations
- Use **TailwindCSS** for styling and layout.
- Implement components using **shadcn/ui** and **Radix UI** to ensure a good user experience.
- Use Lucide/icons

### Tasks
1. Design structure and necessary components.
2. Leave a empty section on the right for the other components
3. Style the navbar using TailwindCSS classes.
4. Implement logic to highlight the active element using **Class Variance Authority**.

### Figma Reference
You can use the Figma design linked [here](https://www.figma.com/design/jmGSfuyhg1ger0yWBTxES3/PayStell-Dashboard?m=auto&t=6qcP1zY6JCdYWxLL-1) as a reference, but feel free to use the previously mentioned components as a guide.

**Comment by Jemiiah** [comment] 2024-11-21 14:07
Hello I'm a frontend developer in web3 I have contributed in previous OD Hacks  i have made over 70+ contribution in past OD Hacks I intend in solving this issue with the following approach :

**Comment by Kingsuite** [comment] 2024-11-21 14:13
Can I take care of this issue?

**Comment by petersdt** [comment] 2024-11-21 14:21
Is this issue still available?

**Comment by Jemiiah** [comment] 2024-11-21 14:24
I’d like toHello I'm a frontend developer in web3 I have contributed in previous OD Hacks  i have made over 70+ contribution in past OD Hacks I intend in solving this issue with the following approach :

Step 1: Structuring the Navbar
First, I'll create the layout for the navbar. I'll make sure it sits on the left-hand side of the dashboard and leaves an empty section to the right for other components, as specified. Using a flexbox layout will help me achieve this cleanly. I'll set up placeholders for the links (Dashboard, Your Money, Payment Links, Sales, and Settings) and use a responsive design approach from the start.

Step 2: Styling with TailwindCSS
Since TailwindCSS is my tool of choice for styling, I'll ensure the navbar has a modern and sleek look:

I'll use Tailwind utility classes for spacing, colors, and responsive adjustments.
For the active link, I'll use hover effects and dynamic classes to ensure it's visually distinct.
I'll also ensure it's responsive so it works seamlessly across devices, using Tailwind's sm, md, and lg breakpoints.
Step 3: Adding Interactivity
For interactivity, I'll use Class Variance Authority (CVA) to manage the styles for active and inactive links dynamically. I’ll also set up logic to detect the current route so that the active link is highlighted. I'll rely on useLocation (React Router) or usePathname (Next.js) to handle this smoothly.

Icons will make the navbar more intuitive, so I'll integrate Lucide icons to match each link’s purpose. For example:

HomeIcon for the dashboard.
DollarSignIcon for "Your Money."
LinkIcon for "Payment Links."
Step 4: Ensuring Accessibility
Accessibility is critical, so I’ll:

Make sure all links are keyboard accessible using tabindex and provide meaningful aria-labels.
Style focus states using Tailwind to meet WCAG guidelines.
Test with screen readers to confirm the navbar works well for all users.
Step 5: Polishing with Components
I’ll use shadcn/ui and Radix UI to create reusable components for the navbar links. These libraries will help me deliver a polished user experience while keeping the code modular and clean.

 work on this.

**Comment by wheval** [comment] 2024-11-21 14:24
Hello @MPSxDev, I'm Wheval a  frontend developer with multiple experiences working with React, Tailwindcss, Nextjs and Shadcn. I am also a good contributor on Onlydust. Can i work on this?
Here's how I would do this,
I would go through the current codebase to understand how it's structured.
I would then implement a side navbar component using Shadcn and the linked figma file, the sidebar would contain all the links you listed above. I would ensure the sidebar is responsive on all screen sizes.
I would also implement interactivity so a user can know when a link is active or clicked using Class Variaince authority.
Please assign, Thank you.

ETA is 1 day.

**Comment by derianrddev** [comment] 2024-11-21 14:34
My Background and How It Can Be Leveraged
Hello, my name is Derian Rodríguez. I am a passionate software engineer with over one year of experience. I am part of the Dojo Coding Community and have been actively contributing to open-source projects through OnlyDust. I have experience in frontend development using JavaScript/TypeScript, React, and Next.js. I would love to continue contributing and supporting the development of this project.

How I Plan on Tackling This Issue
I will create the navbar using shadcn/ui and Radix UI, making sure to include the specified sections (Dashboard, Your Money, Payment Links, Sales, Settings), following the Figma design.
I will style the navbar with TailwindCSS to make it responsive and highlight the active link using Class Variance Authority.
I will add Lucide/icons.
I will test the functionality to ensure everything works correctly.

**Comment by BrunoAmbricca** [comment] 2024-11-21 14:35
I would like to work on this issue

**Comment by martinvibes** [comment] 2024-11-21 14:38
Can I take care of this issue?
i'm a frontend dev and a blockchain dev please kindly assign :)

**Comment by coxmars** [comment] 2024-11-21 14:54
Hi @MPSxDev, I'm a software developer with 2+ years of experience and I have worked with backend technologies such as Cairo, Java, C# and frontend with React, NextJS, JS/TS. Also, I'm a member of the Dojo Coding community here in CR and I have made contributions in Cairo VM Go, Cairo VM TS, Cairo Lints etc. Likewise, I’m a Cairo developer working in ByteBuildersLabs creating on-chain games using the Dojo framework.

This is my approach:

- I will review the contributor guide and any existing components to ensure the navbar follows the project’s structure and styling conventions.
- I’m going to create a reusable Navbar component, ensuring it matches the design provided.
- I’ll make sure the component is responsive and can be easily integrated into all routes.
- Finally, I will test the component across different routes to verify that it works as intended visually.

ET: 3 days.

**Comment by Unickhub** [comment] 2024-11-21 14:59
I'd be happy to do this.

**Comment by Benjtalkshow** [comment] 2024-11-21 15:07
Could I try solving this?

**Comment by KevinLatino** [comment] 2024-11-21 15:18
Hello @MPSxDev My name is Kevin Latino, and I'm a Frontend Developer and active open-source contributor. I'm a member of Dojo Coding ⛩️, a thriving Web3 community in Costa Rica. I have experience with React, Next.js, and TypeScript, also I have experience in data fetching and API integrations and I recently won the LATAM Hackathon hosted by Base. I've also contributed to projects in ecosystems like Starknet and Stellar.

I'll implement a responsive left-side navbar for the dashboard using TailwindCSS. The navbar will include links for "Dashboard," "Your Money," "Payment Links," "Sales," and "Settings," each linking to their respective routes. It will feature interactive visual effects to highlight the active link using Class Variance Authority and ensure compliance with accessibility guidelines. I'll integrate Lucide icons for each section and use shadcn/ui and Radix UI for consistent components. The right side will remain empty for other components, and I'll refer to the Figma design for alignment with the overall UI.

Here is an example of a Frontend Project that I have made: 
https://buildmyevent.xyz/

**Comment by Michaelkingsdev** [comment] 2024-11-21 15:21
May I handle this issue? I am an experienced frontend developer.

**Comment by od-hunter** [comment] 2024-11-21 15:34
This is my first time contributing to this ecosystem and I would love to be given the opportunity. I am a blockchain developer, and my experience includes html, css, react, javaScript, typescript, solidity and cairo.

To solve this issue I’ll take the following steps:

1.⁠ ⁠I’ll create a Navbar component that includes navigation links for sections like /dashboard, /dashboard/money, /dashboard/links, /dashboard/sales, and /dashboard/settings. Then I’ll use React Router (<Link>) to handle routing between different dashboard sections.
2.⁠ ⁠⁠Then I’ll use TailwindCSS for styling, with responsive classes (e.g., lg:flex, lg:hidden) to adapt the navbar for both desktop and mobile views.
3.⁠ ⁠⁠I’ll highlight the active link by comparing the current route (window.location.pathname) with the target link. Use CVA (Class Variance Authority) pattern (or classnames) to dynamically apply styles based on the active state
4.⁠ ⁠⁠I’ll use TailwindCSS utility classes for layout (flex, items-center, space-x-3) and conditional styling (e.g., bg-gray-700 for active links). I’ll also add hover effect.
5.⁠ ⁠⁠I’ll ensure semantic HTML (<nav>, <ul>, <li>) and include aria-current="page" on active links for better screen reader support.

Please assign me I’m ready to work.

**Comment by MullerTheScientist** [comment] 2024-11-21 16:14
I'd love to handle this task

**Comment by emmz3230** [comment] 2024-11-21 16:28
I am a front-end developer specializing in responsive web design,
device-compatible email templates, 3D web integration,
and technical writing on programming topics. I also contribute
to open-source documentation and help build documentation sites.

i will create a responsive sidebar that have a toggle and it is responsive for all device and make sure i leave a blank sidebar on the right for other components using the design as a references .

glad to work on this 

Thanks

**Comment by LazarusAA** [comment] 2024-11-21 17:08
Hi! I'm Alvaro Lazarus, a developer from Dojo Coding ⛩️ with experience in both front-end and back-end development, and I would love to tackle this issue. With my proficiency in TypeScript, React, NextJS and experience working on the front-end aspects of my last few hackathons, I'm confident that I can contribute to this project efficiently.

My workflow:

- Create a responsive left-side navbar with the specified dashboard links
- Use TailwindCSS, shadcn/ui, Radix UI, and Lucide/icons for styling and 
components
- Implement visual effects to highlight the active link using Class Variance Authority
- Ensure accessibility compliance and leave an empty right section for other components

ETA: 48 hrs

**Comment by chibokaxavier** [comment] 2024-11-21 17:26
Hi, i am Chiboka Emmanuel  a full-stack web developer who enjoys creating solutions and applications that look great and work smoothly. I would really love to be assigned this issue and work on this project.

**Comment by DanielEmmanuel1** [comment] 2024-11-21 17:34
I'd be happy to do this.

Hello, I'm Deon a  Full-Stack developer with high expertise in making crisp & responsive UI designs

How i hope to handle this task:

- Structuring a responsive left-side navigation bar with links to all sections.
- Adding interactivity using Class Variance Authority for active state highlights.
- Styling with TailwindCSS and enhancing usability with shadcn/ui, Radix UI, and Lucide icons.
- Leaving a placeholder section on the right for additional components.

ETA: 48 hours.

**Comment by Yunusabdul38** [comment] 2024-11-21 18:00
I’d like to work on this,
and make sure it meets the requirements

**Comment by pablomadrigal** [comment] 2024-11-21 19:56
# I'm Pablo Madrigal. 
## I'm a Fullstack Developer and also part of Dojo Coding 🔥

## Problem
Implement a Navbar in the Dashboard

## Solution
Create a reusable Navbar component for navigation through the application
I would create a responsive component that could adapt to the different screen resolutions
The navbar is going to be able to adapt to different needs in the future
Also, I would recommend modifying the current layout component to implement the navigation and changes between logged users and public view, this could be implemented at the same time

## Estimated time
I'm going to have everything ready in less than 48 hours from the bug assignation

**Comment by vestor-dev** [comment] 2024-11-21 20:04
hey sir I'd like to handle this task.
i'm a frontend developer with experience
i would really love to contribute to your project 
kindly assign :)

**Comment by jedstroke** [comment] 2024-11-21 22:09
May I be assigned to this?

**Comment by Kaminar-i** [comment] 2024-11-22 00:45
Mind if I take this issue?
i'm new and would love to work on this 
please assign me

**Closed** 2024-11-28 00:25 UTC
Labels: ODHack10, difficult: medium
