### ISSUE TITLE
Make .github/workflows directory

### ISSUE THREAD

**Issue by MPSxDev** [PayStell/paystell-website#3] opened 2024-11-04 15:17 UTC
Create the .github/workflows directory to store GitHub Actions workflows, enabling automated processes like testing, building, and deployment within the repository.

**Comment by Jonatan-Chaverri** [comment] 2024-11-05 20:00
Can I work on this one?

**Comment by josephpdf** [comment] 2024-11-11 16:44
Hi!, my name is Joseph Poveda. 
I am a student of the Systems Programming degree, I am a recent member of the Dojo Coding community, where I am getting started in the world of Web3. 
I have basic knowledge of different programming languages ​​and thanks to this I hope to be able to resolve the issue.
To address this issue, I would begin by creating a .github/workflows directory within the repository to store GitHub Actions workflows. This directory will allow us to set up automated workflows for testing, building, and deployment, streamlining project processes. I would then add a basic YAML workflow configuration, such as a test or build action, to verify that the setup is working as intended. This approach ensures all necessary workflows can be managed and updated in a centralized location.

**Comment by salazarsebas** [comment] 2024-11-12 17:37
My background
As a member of the Dojo Coding community, I have experience in web2 and traditional technologies, as for web3 I have only been working for a few months and I have managed to make a contribution, however, it is not an impediment for me to do my best in this issue, I will devote the necessary effort to contribute to the OSS.

How I plan on tackling this issue
To solve this issue, I will perform the following steps:

- Analyze what is required.
- Study to be prepared to make the .github/workflows.
- Submit for review.

**Comment by od-hunter** [comment] 2024-11-14 13:51
Hello can I be assigned this please? Below are some of the documentations I've done that were merged:

https://github.com/dojoengine/book/pull/308, https://github.com/keep-starknet-strange/joyboy/pull/143, https://github.com/Scaffold-Stark/ss2-docs/pull/31, https://github.com/horuslabsio/Starknet-Scaffold/pull/94,
https://github.com/Hyle-org/examples/pull/15.

**Comment by Villarley** [comment] 2024-11-14 17:49
I’m a Dojo Coding member and an active contributor to the OSS. I’ve worked on several Web3 projects, including contributions to stellar projects and building on StarkNet. I also have solid experience with React, and as a Web3 hackathon buildathon winner.

For this issue, I’d like to create the .github/workflows directory to enable automated actions like testing, building, and deployment in the repository. I’ll ensure the workflows are structured to support the team’s needs and scalability.

**Comment by ryzen-xp** [comment] 2024-11-15 17:57
May I be assigned to this?

**Comment by martinvibes** [comment] 2024-11-16 08:44
hey @MPSxDev can i work on this issue and write a well detailed doc when the odhack starts :)

**Comment by wheval** [comment] 2024-11-19 12:53
Hello @MPSxDev, Can I handle this task?

**Comment by GideonBature** [comment] 2024-11-20 07:24
Can you please assign this to me?

**Comment by MrRoudyk** [comment] 2024-11-20 12:45
May I be assigned to this?

**Comment by Amarjeet325** [comment] 2024-11-21 05:22
Hi, I am a proficient MERN stack developer with experience in full-stack development. I believe I can contribute effectively to this project. Could you kindly /assign this issue/task to me? Thank you!

**Comment by raizo07** [comment] 2024-11-21 14:03
Could I be assigned to this? I'm a software developer with over four years of experience

**Comment by Unickhub** [comment] 2024-11-21 15:00
Mind if I try this one?

**Comment by ShantelPeters** [comment] 2024-11-21 15:10
Is it okay if I tackle this?

**Comment by salazarsebas** [comment] 2024-11-21 17:03
My background
As a member of the Dojo Coding community, I have experience in web2 and traditional technologies, as for web3 I have only been working for a few months and I have managed to make a contribution, however, it is not an impediment for me to do my best in this issue, I will devote the necessary effort to contribute to the OSS.

How I plan on tackling this issue
To solve this issue, I will perform the following steps:

- Analyze what is required.
- Study to be prepared to make the .github/workflows.
- Submit for review.

**Comment by jsandinoDev** [comment] 2024-11-21 20:05
Hi  I'm a full-stack developer from Costa Rica and member of Dojo coding. I've worked on projects using React, Solidity, Cairo, and blockchain tools. My skills in both front-end and back-end development allow me to build scalable and secure solutions for web3 ecosystems.


To solve this issues I will
1.	Understand the Purpose
	•	Identify the tasks you want to automate (e.g., testing, deployment, linting).
	•	Ensure GitHub Actions is appropriate for your needs.
	2.	Set Up the Structure
	•	Create the .github/workflows directory in your repository to house workflow definitions.
	3.	Define Workflow Goals
	•	Plan the events that should trigger the workflows (e.g., push, pull_request).
	•	Decide on the specific actions or jobs the workflow should perform.
	4.	Write Workflow Files
	•	Draft YAML files that outline the automated steps to achieve your goals.
	5.	Test and Iterate
	•	Push the changes to the repository to trigger the workflows and verify they work as expected.
	•	Refine the workflows based on outcomes and project needs.

**Comment by vestor-dev** [comment] 2024-11-21 20:06
hey sir I'd like to handle this task.
i'm a frontend developer with experience
i would really love to contribute to your project 
kindly assign :)

**Comment by Kaminar-i** [comment] 2024-11-22 00:45
Mind if I take this issue?
i'm new and would love to work on this 
please assign me

**Comment by jrmncos** [comment] 2024-11-22 03:08
hey, I'm a Software Engineer in web2, I already implemented some CI with Github actions in other open sources repos. I can do it in this one :)

**Comment by sotoJ24** [comment] 2024-11-22 04:08
Hi team, I'm Josué From Dojo Coding

Here's my proposed solution:

1. **Create the `.github/workflows` directory:** This will serve as the central hub for all GitHub Actions workflows.
2. **Add a simple workflow file:** I'll start with a basic YAML file, such as a `build.yml`, to define a workflow that triggers on pushes to the main branch. This workflow could include:
   - Checking out the code.
   - Running unit tests.
   - Linting the code.
   - Building the project.
3. **Configure the workflow:** I'll specify the events that trigger the workflow, the jobs to be executed, and the steps involved in each job.
4. **Commit and push the changes:** Once the workflow is defined, I'll commit and push the changes to the repository, triggering the workflow execution.

**Comment by mimisavage** [comment] 2024-11-22 07:16
Could I be assigned to this?

**Comment by bruhhgnik** [comment] 2024-11-22 07:58
i have worked on workflow projects before, https://github.com/dipdup-io/stone-packaging/pull/65 heres one example, id love to work on this!

**Comment by hossamanany** [comment] 2024-11-22 09:27
I'd love to work on this!

**Closed** 2024-11-26 23:36 UTC
Labels: documentation, good first issue, ODHack10
